<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jagadish" failures="1" tests="3" name="runners.TestRunner_Signup" time="23.363" errors="0" timestamp="2024-12-22T14:00:03 IST" skipped="0">
  <testcase classname="runners.TestRunner_Signup" name="runScenario" time="8.577"/>
  <testcase classname="runners.TestRunner_Signup" name="runScenario" time="6.081"/>
  <testcase classname="runners.TestRunner_Signup" name="runScenario" time="8.705">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stepdefinitions.signup.user_should_successfully_signup_and_should_be_display(signup.java:69)
at âœ½.User should successfully signup and "Sign up successful." should be display(file:///C:/Users/Jagadish%20Moharana/OneDrive/Desktop/New%20folder%20(2)/DemoBlaze_Cucumber_project/src/test/resources/features/Signup.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runners.TestRunner_Signup -->
